import type { Metadata } from "next";
import { DashboardShell } from "@/components/dashboardShell";

export const metadata: Metadata = {
  title: "Dashboard - Revoke",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <DashboardShell>{children}</DashboardShell>;
}
