import type { Metadata } from "next";
import { DashboardSidebar } from "@/components/dashboardSidebar";
import { DashboardNavbar } from "@/components/dashboardNavbar";

export const metadata: Metadata = {
  title: "Dashboard - Revoke",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex min-h-screen">
      <DashboardSidebar />
      <div className="flex flex-1 flex-col">
        <DashboardNavbar />
        <main className="flex-1 p-6 dark:bg-[#101010] bg-zinc-100">
          {children}
        </main>
      </div>
    </div>
  );
}
